### DISCUSSION TITLE
How to setup DRAWIO_CONFIG variate in docker-compose.yaml

### DISCUSSION THREAD

**Discussion by pengshp** [jgraph/docker-drawio#39] [Q&A]
Hello!
`DRAWIO_CONFIG` variate, 
What should I write after the variable?
I can't understand! it's a path for json file or content of json file?
Please give example DRAWIO_CONFIG for self-contained.

Thanks!

**Comment by davidjgraph** [comment]
You don't set it in the compose, you set window.DRAWIO_CONFIG in the PreConfig.js file and mount it into docker.

**Comment by yauhenipakala** [comment]
@pengshp just put json as string:

```yaml
services:
  drawio:
    image: jgraph/drawio:28.2.3
    environment:
      - DRAWIO_CONFIG: '{"customFonts":[]}'

    # ...
```

More about config format: https://www.drawio.com/doc/faq/configure-diagram-editor

> [!NOTE]
> `DRAWIO_CONFIG` used to construct PreConfig.js file:
> https://github.com/jgraph/docker-drawio/blob/e12d208d24aa04895f4561cfa23b824be5f34fe9/main/docker-entrypoint.sh#L67
