### ISSUE TITLE
URI malformed

### ISSUE THREAD

**Issue by xsolinsx** [jgraph/docker-drawio#127]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, ~~without success~~ I've found something but it does not apply to my case/does not have a solution/refers to a very old version.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
I open my drawio container from the web and get a pop-up on firefox desktop saying "The URI is malformed.", this does not allow me to use drawio in any way even if I close the pop-up.
On mobile I get a "different" error which might point to a resolution: "XMLHttpRequest.open: 'http://localhost:8080notifications' is not a valid URL."

**To Reproduce**
1. Use docker-compose provided below
2. Go to the URL of drawio
3. See error

**Expected behavior**
Drawio opens correctly

**Screenshots**
The following is a picture of what happens after I dismiss the pop-up
![immagine](https://github.com/jgraph/drawio/assets/16761752/1e0fd347-dcca-40a6-b7c5-006cc0dbce4c)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.0.z (I tried all versions from 22.0.0 to 22.0.7), it works with 21.8.2

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox
 - Browser Version 118.0.2

**Smartphone (please complete the following information):**
 - Device: Motorola Moto G8 Power
 - OS: Android 11
 - Browser Firefox
 - Version 119.0

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
yes

**Additional context**
docker-compose (healthcheck says container is healthy)
```yaml
version: "3"

services:
  drawio:
    container_name: drawio
    image: jgraph/drawio:22.0.7
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080", "||", "exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s
  traefik:
    container_name: traefik
    image: traefik:3.0
    restart: always
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    volumes:
      - traefik_certs:/home/traefik/certs:rw
      - traefik_conf:/etc/traefik:rw
      - traefik_logs:/home/traefik/logs:rw
      - traefik_file_dynamic_conf:/home/traefik/file_dynamic_conf:ro
      - traefik_secrets:/run/secrets:ro
```

I use traefik (container) as webserver and this is the file config for drawio
```
http:
  services:
    drawio:
      loadBalancer:
        servers:
          - url: http://drawio:8080

  routers:
    drawio:
      service: drawio
      rule: Host(`drawio.example.com`)||Path(`/drawio`)
      tls:
        certResolver: lets_encrypt
```
