### ISSUE TITLE
Exporting to PDF goes to https://convert.diagrams.net/node/export

### ISSUE THREAD

**Issue by kabaga** [jgraph/docker-drawio#139]
Is this a new behavior of the drawio container?
When I export to PNG, JPEG, SVG, or VSDX, it does go to https://convert.diagrams.net/.

I am running the latest version v22.0.8
Below is my docker-compose.yml content
```
version: '3.5'
services:
  drawio:
    image: jgraph/drawio
    container_name: drawio
    restart: unless-stopped
    ports:
      - 8081:8080
      - 8443:8443
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://10.0.7.20:8081 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s
```

**Comment by davidjgraph** [comment]
That's not right. What's in your preconfig file? https://github.com/jgraph/drawio/blob/dev/src/main/webapp/js/PreConfig.js

**Comment by kabaga** [comment]
How do I check my preconfig file?

**Comment by kabaga** [comment]
> That's not right. What's in your preconfig file? https://github.com/jgraph/drawio/blob/dev/src/main/webapp/js/PreConfig.js

I think I found it:

```
(function() {
  try {
	    var s = document.createElement('meta');
	    s.setAttribute('content', 'default-src \'self\'; script-src \'self\' https://storage.googleapis.com https://apis.google.com https://docs.google.com https://code.jquery.com \'unsafe-inline\'; connect-src \'self\' https://*.dropboxapi.com https://api.trello.com https://api.github.com https://raw.githubusercontent.com https://*.googleapis.com https://*.googleusercontent.com https://graph.microsoft.com https://*.1drv.com https://*.sharepoint.com https://gitlab.com https://*.google.com https://fonts.gstatic.com https://fonts.googleapis.com; img-src * data:; media-src * data:; font-src * about:; style-src \'self\' \'unsafe-inline\' https://fonts.googleapis.com; frame-src \'self\' https://*.google.com;');
	    s.setAttribute('http-equiv', 'Content-Security-Policy');
 	    var t = document.getElementsByTagName('meta')[0];
      t.parentNode.insertBefore(s, t);
  } catch (e) {} // ignore
})();
window.DRAWIO_BASE_URL = 'http://localhost:8080';
window.DRAWIO_SERVER_URL = window.DRAWIO_BASE_URL + '/';
window.DRAWIO_VIEWER_URL = '';
window.DRAWIO_LIGHTBOX_URL = '';
window.DRAW_MATH_URL = 'math/es5';
window.DRAWIO_CONFIG = null;
urlParams['sync'] = 'manual'; //Disable Real-Time
urlParams['db'] = '0'; //dropbox
urlParams['gh'] = '0'; //github
urlParams['tr'] = '0'; //trello
urlParams['gapi'] = '0'; //Google Drive
urlParams['od'] = '0'; //OneDrive
urlParams['gl'] = '0'; //Gitlab
```

**Comment by davidjgraph** [comment]
OK, add window.EXPORT_URL to point at your export server.

**Comment by m-mohamedin** [comment]
Please have a look at https://github.com/jgraph/docker-drawio/blob/dev/self-contained/docker-compose.yml which contains a local export server

**Comment by kabaga** [comment]
> OK, add window.EXPORT_URL to point at your export server.

If the export server is the same as the drawio host, should this be 127.0.0.1:8000 or the container name with the port?
I tried both but it is going to the base url "DRAWIO_BASE_URL=https://10.0.7.20:8085".
Below is my new docker-compose file:
```
version: '3'
services:
  plantuml-server:
    image: plantuml/plantuml-server
    expose:
      - "8080"
    networks:
      - drawionet
    volumes:
      - fonts_volume:/usr/share/fonts/drawio
  image-export:
    image: jgraph/export-server
    expose:
      - "8001"
    networks:
      - drawionet
    volumes:
      - fonts_volume:/usr/share/fonts/drawio
    environment:
      - DRAWIO_BASE_URL=${DRAWIO_BASE_URL}
  drawio:
    image: jgraph/drawio
    ports:
      - "8084:8443"
      - "8085:8080"
    links:
      - plantuml-server:plantuml-server
      - image-export:image-export
    depends_on:
      - plantuml-server
      - image-export
    networks:
      - drawionet
    environment:
      - DRAWIO_SELF_CONTAINED=1
      - PLANTUML_URL=http://plantuml-server:8080/
      - EXPORT_URL=http://image-export:8001/
networks:
  drawionet:

volumes:
  fonts_volume:

```
