### ISSUE TITLE
Nginx redirect and drawio config

### ISSUE THREAD

**Issue by manuel-florido** [jgraph/docker-drawio#155]
Hi, 

I am trying to use drawio self-hosted and I have some questions.

1. I am using Nginx because I wanted to require login, so this is my Nginx server configuration:

  server_name myserver.com;
  location / {
    auth_basic           "Administrator’s Area";
    auth_basic_user_file /etc/apache2/.htpasswd; 
    proxy_pass http://127.0.0.1:8080;
    client_max_body_size 9000m;
    proxy_redirect off;
  }

It works fine with Drawio but when I tried to export a PDF It fails. Do you know how to configure a login correctly?

2. How do I config Drawio with a .json?
I tried to create a .json, put the config and write the path in DRAWIO_CONFIG= on docker-compose.yml, did not work for me.
Now I am using this:

- DRAWIO_CONFIG='{"servicesConfig":{"export":false,"local":false,"drive":true,"sharepoint":false,"onedrive":false,"github":false,"gitlab":false,"trello":false,"confluence":false,"jira":false},"DrawConfig":{"defaultLang":"es"}}'

It works except the language, can you help me to config the default language to spanish?

Thank you.

**Comment by TristisOris** [comment]
have a same problem with PDF export and nginx reverse proxy.

```
  drawio:
    image: jgraph/drawio
    ports:
      - 45921:8080
      - 45922:8443
    environment:
      - DRAWIO_BASE_URL=${DRAWIO_BASE_URL}
      - EXPORT_URL=http://image-export:8000/
```

on export it go to `https://domain.name:45921/service/0` and say `Secure Connection Failed`.


 if i use https port at nginx proxy and NC settings, i got endless loading.

![image](https://github.com/user-attachments/assets/05049de9-921e-48e6-90b2-2d091948995a)
