### ISSUE TITLE
Can't use self-host with viewer url 

### ISSUE THREAD

**Issue by noopn** [jgraph/docker-drawio#167]
- [x]  Already config environment

But can't use self-host with viewer url.
Please help me check where the following has errors.
 
```yml
expose:
      - "8080"
    networks:
      - drawionet
    volumes:
      - fonts_volume:/usr/share/fonts/drawio
  image-export:
    image: jgraph/export-server
    expose:
      - "8000"
    networks:
      - drawionet
    volumes:
      - fonts_volume:/usr/share/fonts/drawio
    environment:
      - DRAWIO_BASE_URL=https://mysite:26410
  drawio:
    image: jgraph/drawio
    ports:
      - "26413:8443"
      - "26410:8080"
    links:
      - plantuml-server:plantuml-server
      - image-export:image-export
    depends_on:
      - plantuml-server
      - image-export
    networks:
      - drawionet
    environment:
      - DRAWIO_SELF_CONTAINED=1
      - PLANTUML_URL=http://plantuml-server:8080/
      - EXPORT_URL=http://image-export:8000/
      - DRAWIO_BASE_URL=https://mysite:26410
      - DRAWIO_SERVER_URL=https://mysite:26410/
      - DRAWIO_VIEWER_URL=https://mysite:26410/js/viewer.min.js
      - DRAWIO_LIGHTBOX_URL=https://mysite:26410/
networks:
  drawionet:

volumes:
  fonts_volume:
```
