### ISSUE TITLE
Notifications 404 not found

### ISSUE THREAD

**Issue by chary1112004** [jgraph/docker-drawio#187]
Hi,

We are running the latest docker version with helm chart in embed mode.

Web browser error console says:
app.min.js:287
```
https://{drawio domain}/notifications 404 (Not Found)
```

![Image](https://github.com/user-attachments/assets/bc92d20e-ca9a-4a51-92b5-0e363be1adc2)

```
drawio:
  # name is used to overwrite for deployment name
  fullnameOverride: "drawio"

  replicas: 1

  workload:
    main:
      podSpec:
        containers:
          main:
            env:
              DRAWIO_BASE_URL: "https://{{ drawio domain }}"

  securityContext:
    container:
      capabilities:
        drop:
          - ALL
      # readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1001
      allowPrivilegeEscalation: false
      privileged: false
```

Any suggestion to resolve this issue would be very much appreciated!

Thanks!
