### ISSUE TITLE
drawio docker image >27.0.2 isn't working anymore

### ISSUE THREAD

**Issue by 1of16** [jgraph/docker-drawio#188]
hi,
so far I used the following docker compose file to start drawio:

```
services:
  plantuml-server:
    image: plantuml/plantuml-server:latest
    container_name: drawio_ps
    expose:
      - "8080"
    networks:
      - drawionet
#    volumes:
#      - fonts_volume:/usr/share/fonts/drawio
    restart: unless-stopped
  image-export:
    image: jgraph/export-server:latest
    container_name: drawio_ie
    expose:
      - "8000"
    networks:
      - drawionet
#    volumes:
#      - fonts_volume:/usr/share/fonts/drawio
    environment:
      - DRAWIO_BASE_URL=https://example.com/
    restart: unless-stopped
  drawio:
#    image: jgraph/drawio:latest
    image: jgraph/drawio:27.0.2
    container_name: drawio
    ports:
      - "10.20.0.1:38443:8443"
      - "10.20.0.1:38080:8080"
    links:
      - plantuml-server:plantuml-server
      - image-export:image-export
    depends_on:
      - plantuml-server
      - image-export
    networks:
      - drawionet
    environment:
      - LETS_ENCRYPT_ENABLED=false
      - DRAWIO_USE_HTTP=1
      - DRAWIO_SELF_CONTAINED=1
      - PLANTUML_URL=http://plantuml-server:8080/
      - EXPORT_URL=http://image-export:8000/
      - DRAWIO_BASE_URL=https://example.com/
      - DRAWIO_SERVER_URL=https://example.com
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s

networks:
  drawionet:
```

after upgrading to 27.0.5 or 27.0.9 or even the latest tag image the drawio is unhealthy and I get a tomcat "http 404 " error.
the logs (docker logs drawio) are looking identical, and I can't see a reason for the problem:
```
Init PreConfig.js
Updating Tomcat context path to '/example.com'
(function() {
  try {
            var s = document.createElement('meta');
            s.setAttribute('content', 'default-src \'self\'; script-src \'self\' https://storage.googleapis.com https://apis.google.com https://docs.google.com https://code.jquery.com \'unsafe-inline\'; connect-src \'self\' https://*.dropboxapi.com https://api.trello.com https://api.github.com https://raw.githubusercontent.com https://*.googleapis.com https://*.googleusercontent.com https://graph.microsoft.com https://*.1drv.com https://*.sharepoint.com https://gitlab.com https://*.google.com https://fonts.gstatic.com https://fonts.googleapis.com; img-src * data:; media-src * data:; font-src * about:; style-src \'self\' \'unsafe-inline\' https://fonts.googleapis.com; frame-src \'self\' https://*.google.com;');
            s.setAttribute('http-equiv', 'Content-Security-Policy');
            var t = document.getElementsByTagName('meta')[0];
      t.parentNode.insertBefore(s, t);
  } catch (e) {} // ignore
})();
window.EXPORT_URL = '/service/0'; //This points to ExportProxyServlet which uses the local export server at port 8000. This proxy configuration allows https requests to the export server via Tomcat.
window.PLANT_URL = '/service/1';
window.DRAWIO_SERVER_URL = 'https://example.com';
window.DRAWIO_BASE_URL = 'https://example.com';
window.DRAWIO_VIEWER_URL = '';
window.DRAWIO_LIGHTBOX_URL = '';
window.DRAW_MATH_URL = 'math/es5';
window.DRAWIO_CONFIG = null;
urlParams['sync'] = 'manual'; //Disable Real-Time
urlParams['db'] = '0'; //dropbox
urlParams['gh'] = '0'; //github
urlParams['tr'] = '0'; //trello
urlParams['gapi'] = '0'; //Google Drive
urlParams['od'] = '0'; //OneDrive
urlParams['gl'] = '0'; //Gitlab
Init PostConfig.js
window.VSD_CONVERT_URL = null;
window.ICONSEARCH_PATH = null;
EditorUi.enableLogging = false; //Disable logging
window.EMF_CONVERT_URL = null;
EditorUi.enablePlantUml = true; //Enables PlantUML
App.prototype.isDriveDomain = function() { return true; }
Generating Self-Signed certificate
Keystore type: PKCS12
Keystore provider: SUN

Your keystore contains 1 entry

Alias name: selfsigned
Creation date: Jun 11, 2025
Entry type: PrivateKeyEntry
Certificate chain length: 1
Certificate[1]:
Owner: CN=draw.example.com, OU=Cloud Native Application, O=example inc, L=Paris, ST=Paris, C=FR
Issuer: CN=draw.example.com, OU=Cloud Native Application, O=example inc, L=Paris, ST=Paris, C=FR
Serial number: 1cb2856b
Valid from: Wed Jun 11 19:15:48 UTC 2025 until: Fri Apr 20 19:15:48 UTC 2035
Certificate fingerprints:
         SHA1: C6:06:3A:35:BC:0F:65:24:C2:D3:F1:7E:64:07:06:E1:13:67:E5:58
         SHA256: E6:6D:EF:A1:A7:B3:05:44:23:49:D9:FC:90:17:BD:6B:86:08:96:08:FF:F4:D9:EF:55:77:F4:71:8C:A6:D1:44
Signature algorithm name: SHA256withRSA
Subject Public Key Algorithm: 2048-bit RSA key
Version: 3

Extensions:

#1: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: 2B 8B 6B B4 6F A2 24 AF   29 A3 D8 E6 67 DC 32 D2  +.k.o.$.)...g.2.
0010: C0 06 BB 49                                        ...I
]
]



*******************************************
*******************************************


Append https connector to server.xml
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
11-Jun-2025 19:15:51.853 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.105
11-Jun-2025 19:15:51.871 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          May 7 2025 18:36:02 UTC
11-Jun-2025 19:15:51.872 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.105.0
11-Jun-2025 19:15:51.872 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
11-Jun-2025 19:15:51.872 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            6.1.0-37-amd64
11-Jun-2025 19:15:51.872 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
11-Jun-2025 19:15:51.872 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /opt/java/openjdk
11-Jun-2025 19:15:51.872 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.27+6
11-Jun-2025 19:15:51.872 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Eclipse Adoptium
11-Jun-2025 19:15:51.872 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
11-Jun-2025 19:15:51.872 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
11-Jun-2025 19:15:51.913 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
11-Jun-2025 19:15:51.914 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang.invoke=ALL-UNNAMED
11-Jun-2025 19:15:51.914 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang.reflect=ALL-UNNAMED
11-Jun-2025 19:15:51.914 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
11-Jun-2025 19:15:51.914 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util=ALL-UNNAMED
11-Jun-2025 19:15:51.914 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
11-Jun-2025 19:15:51.914 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
11-Jun-2025 19:15:51.915 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
11-Jun-2025 19:15:51.915 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
11-Jun-2025 19:15:51.915 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
11-Jun-2025 19:15:51.915 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
11-Jun-2025 19:15:51.915 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dsun.io.useCanonCaches=false
11-Jun-2025 19:15:51.915 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
11-Jun-2025 19:15:51.916 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
11-Jun-2025 19:15:51.916 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
11-Jun-2025 19:15:51.916 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
11-Jun-2025 19:15:51.921 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
11-Jun-2025 19:15:51.933 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded Apache Tomcat Native library [1.3.1] using APR version [1.7.2].
11-Jun-2025 19:15:51.933 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true], UDS [true].
11-Jun-2025 19:15:51.933 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
11-Jun-2025 19:15:51.943 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 3.0.13 30 Jan 2024]
11-Jun-2025 19:15:52.791 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
11-Jun-2025 19:15:52.844 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["https-openssl-nio-8443"]
11-Jun-2025 19:15:53.255 INFO [main] org.apache.tomcat.util.net.AbstractEndpoint.logCertificate Connector [https-openssl-nio-8443], TLS virtual host [draw.example.com], certificate type [UNDEFINED] configured from keystore [/usr/local/tomcat/.keystore] using alias [tomcat] with trust store [null]
11-Jun-2025 19:15:53.470 INFO [main] org.apache.tomcat.util.net.AbstractEndpoint.logCertificate Connector [https-openssl-nio-8443], TLS virtual host [draw.example.com], certificate type [UNDEFINED] configured from keystore [/usr/local/tomcat/.keystore] using alias [tomcat] with trust store [null]
11-Jun-2025 19:15:53.474 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [2295] milliseconds
11-Jun-2025 19:15:53.613 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
11-Jun-2025 19:15:53.617 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.105]
11-Jun-2025 19:15:54.373 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
11-Jun-2025 19:15:54.399 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/draw]
11-Jun-2025 19:15:54.619 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
11-Jun-2025 19:15:54.625 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/draw] has finished in [226] ms
11-Jun-2025 19:15:54.628 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
11-Jun-2025 19:15:54.642 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["https-openssl-nio-8443"]
11-Jun-2025 19:15:54.647 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [1172] milliseconds
```

any help wold be great!
thank you!

**Comment by davidjgraph** [comment]
What if you remove the trailing / from the end of DRAWIO_BASE_URL ?

**Comment by 1of16** [comment]
> What if you remove the trailing / from the end of DRAWIO_BASE_URL ?

same result

**Comment by 1of16** [comment]
same Problem with 27.1.6 :(
any ideas ?

**Comment by 1of16** [comment]
and still the same problem with 28.0.6 :(

@davidjgraph any idea? any more logs or something I can provide?
after changing back to 27.0.2 it is working finde....I am confused :(

**Comment by jbardi** [comment]
I am having the exact same issue with all docker versions newer than 27.0.2, which all end in a tomcat "http 404 " error, but downgrading back to 27.0.2 and everything works fine. Mine is even more simplified:

```
services:
  mydrawio:
      container_name: "mydrawio"
      image: "jgraph/drawio:27.0.2"
      environment:
        - "DRAWIO_USE_HTTP=1"
        - "DRAWIO_SELF_CONTAINED=1"
        - "DRAWIO_BASE_URL=https://drawio.mydomain.com"
        - "DRAWIO_SERVER_URL=https://drawio.mydomain.com"
      ports:
        - "8089:8080"
      restart: "unless-stopped"
```

**Comment by jbardi** [comment]
I was able to fix this by adding a "/" on the servers URL. I also remove DRAWIO_BASE_URL as it is automatically set to the value of the server URL if it is not present, so now I have this and it works on 28.0.7:

```
services:
  mydrawio:
      container_name: "mydrawio"
      image: "jgraph/drawio:27.0.2"
      environment:
        - "DRAWIO_USE_HTTP=1"
        - "DRAWIO_SELF_CONTAINED=1"
        - "DRAWIO_SERVER_URL=https://drawio.mydomain.com/"
      ports:
        - "8089:8080"
      restart: "unless-stopped"
```

On 27.02 and earlier, the "/" at the end of the URL was not necessary, but apparently now it is required.

**Comment by 1of16** [comment]
wow, thank you @jbardi  !

```
services:
  plantuml-server:
    image: plantuml/plantuml-server:latest
    container_name: drawio_ps
    expose:
      - "8080"
    networks:
      - drawionet
#    volumes:
#      - fonts_volume:/usr/share/fonts/drawio
    restart: unless-stopped
  image-export:
    image: jgraph/export-server:latest
    container_name: drawio_ie
    expose:
      - "8000"
    networks:
      - drawionet
#    volumes:
#      - fonts_volume:/usr/share/fonts/drawio
    environment:
      - DRAWIO_BASE_URL=https://example.com/
    restart: unless-stopped
  drawio:
    image: jgraph/drawio:latest
    container_name: drawio
    ports:
      - "10.20.0.1:38443:8443"
      - "10.20.0.1:38080:8080"
    links:
      - plantuml-server:plantuml-server
      - image-export:image-export
    depends_on:
      - plantuml-server
      - image-export
    networks:
      - drawionet
    environment:
      - DRAWIO_USE_HTTP=1
      - DRAWIO_SELF_CONTAINED=1
      - PLANTUML_URL=http://plantuml-server:8080/
      - EXPORT_URL=http://image-export:8000/
      - DRAWIO_SERVER_URL=https://example.com/
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s

networks:
  drawionet:
```

is finally working! thanks!
