### ISSUE TITLE
Error loading file: No file selected

### ISSUE THREAD

**Issue by ovizii** [jgraph/docker-drawio#99]
I'm trying to get the self-contained version running and I can successfully access the drawio instance behind my reverse proxy: https://diagrams.mydomain.tld but all I see is:

![image](https://user-images.githubusercontent.com/837902/216590428-32fca264-c823-4b4f-b9c4-bf25a5dcca8b.png)

What am I missing here? 
btw. I have not connected to any cloud services and don't plan to.

**Comment by ovizii** [comment]
To be clear, I expected to see this, just like when visiting https://draw.io

![image](https://user-images.githubusercontent.com/837902/216591098-30e3ef03-3073-47ce-bf37-fdf8ce7afee6.png)

**Comment by davidjgraph** [comment]
That first screen is the index.html from the docker image?

**Comment by ovizii** [comment]
I don't know where it comes from. I am using a slightly adapted version of https://github.com/jgraph/docker-drawio/blob/dev/self-contained/docker-compose.yml 

I can share it if you have no other ideas about where my problem comes from.

**Comment by ovizii** [comment]
Anyway, here it is, maybe you can spot some dumb change I made :-/

```
version: '2.4'

services:

# https://github.com/jgraph/docker-drawio/tree/dev/self-contained

  drawio:
    image: jgraph/drawio:latest
    container_name: drawio
    hostname: drawio
    restart: "no"
    environment:
      - DRAWIO_SELF_CONTAINED=1
      - PLANTUML_URL=http://drawio-plantuml-server:8080/
      - EXPORT_URL=http://drawio-export-server:8000/
      - DRAWIO_BASE_URL=https://diagrams.mydomain.tld
      - DRAWIO_VIEWER_URL=https://diagrams.mydomain.tld/js/viewer.min.js
      - DRAWIO_LIGHTBOX_URL=https://diagrams.mydomain.tld
    cpus: 1               
    mem_limit: 1G         
    networks:
      - drawio                 
      - traefik                   
    labels:                         
      - "traefik.enable=true"                  
      - "traefik.docker.network=traefik"                  
      - "traefik.http.routers.drawio.tls=true"                 
      - "traefik.http.routers.drawio.entrypoints=websecure"
      - "traefik.http.routers.drawio.middlewares=secHeaders@file"                 
      - "traefik.http.routers.drawio.rule=Host(`diagrams.mydomain.tld`)"
      - "traefik.http.routers.drawio.service=drawio"                
      - "traefik.http.services.drawio.loadbalancer.server.port=8080"

  drawio-plantuml-server:
    image: jgraph/plantuml-server
    container_name: drawio-plantuml-server
    hostname: drawio-plantuml-server
    expose:
      - "8080"
    networks:
      - drawio
    volumes:
      - /usr/share/fonts:/usr/share/fonts

  drawio-export-server:
    image: jgraph/export-server
    container_name: drawio-export-server
    hostname: drawio-export-server
    expose:
      - "8000"
    networks:
      - drawio
    volumes:
      - /usr/share/fonts:/usr/share/fonts
    environment:
      - DRAWIO_SERVER_URL=https://diagrams.mydomain.tld
                                                                                                                                  
networks:
    traefik:            
        external: true        
        name: traefik            
    drawio:            
        external: true            
        name: drawio
```
